# @name listarProdutos
GET {{host}}/products
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

###
# @name buscarProdutoPorId
GET {{host}}/product/4
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

###
# @name buscarProdutoPorNome
GET {{host}}/products/search?keyword=ps5
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

###
# @name deleteProduto
DELETE {{host}}/product/2
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### Adicionar produto
# @name criarProduto
POST {{host}}/product
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
    "name": "ps5 pro",
    "description": "video game",
    "brand": "sony",
    "price": 5300,
    "category": "eletrônico",
    "releaseDate": "2026-07-16",
    "productAvailable": true,
    "stockQuantity": 13
}

###
# @name updateProduto
PUT {{host}}/product/4
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Teste put 4",
  "description": "video game",
  "brand": "sony",
  "price": 5300,
  "category": "eletrônico",
  "releaseDate": "2026-07-16",
  "productAvailable": true,
  "stockQuantity": 13
}
